CREATE TABLE  `fragen` (
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`titel` VARCHAR( 100 ) NOT NULL ,
`inhalt` VARCHAR( 100 ) NOT NULL
`contra` VARCHAR( 255 )
`pro` VARCHAR( 255 )
) ENGINE = INNODB;